name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  checks:
    name: Test Angular client.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup frontend
        run: npm ci --cache ~/.npm
      # TODO: Setup lint
      # - name: Lint
      #   run: npm run lint
      - name: Test
        run: npm run test-ci
